### ISSUE TITLE
Dudas Laboratorio 1

### ISSUE THREAD

**Issue by FernandoDeDiego** [PUC-IIC3141/IIC3413-DB#1]
Hola!
Me quedaron una serie de dudas sobre el laboratorio 1, más específicamente en el testeo y la entrega de este. Cuando dice que tenemos que crear una nueva rama en git a partir de la rama principal del proyecto, se refiere hacer un git branch desde lo que está en PUC-IIC3141? Para qué se usa el repositorio personal?
Cómo puedo testear mi trabajo? y, subirán el archivo storage_test.cc?
Saludos!!!

**Comment by crivero1** [comment]
Hola Fernando, 

Debes cargar la versión de PUC-IIC3141 y hacer una branch en tu repositorio personal. El repositorio personal se usa para corregir tu laboratorio y para que no pueda ser visto por otro compañero. 

Sobre el testeo, publicaremos test lo antes posible parecidos a como será la corrección. Ahora bien, tu puedes revisar que tu solución funciona directamente, no necesitas los test. ¿A qué te refieres con el archivo storage_test.cc?

Por último, te pido que por favor uses el foro del curso o iic3413@ing.puc.cl para colocar dudas. Esta lista de issues es solo para reportar issues de IIC3413-DB. De hecho, ¿puedes subir estas dudas al foro de canvas y te seguimos respondiendo ahí? Gracias!

Saludos!
