### ISSUE TITLE
Bug en create_db.cc

### ISSUE THREAD

**Issue by joseluishaddad** [PUC-IIC3141/IIC3413-DB#3]
Hola, 

Intentando compilar el proyecto me encontré con un problema y es que en la línea 22 del archivo `src>main>create_db.cc` se está intentando hacer `RelationalModel::init();`, sin embargo revisé el método `init()` de `RelationalModel` y por lo que vi, este requiere dos argumentos al ser llamado, como sí se hace por ejemplo en el archivo `check_bpts.cc` en la línea 45.
Lo que faltaría hacer, si se desea usar esa función ahí, es entregarle un `db_folder` y `buffer_size`.

Quedo atento!

Edit: pude ver que este archivo no está en los build targets.. podemos eliminarlo simplemente?

**Comment by cirojas** [comment]
La interfaz de las algunas clases ha ido cambiando a medida que han avanzado los laboratorios. Ahora lo que está en la rama Lab4 es lo que cuenta. El archivo create_db.cc fue renombrado a import_graph.cc. Tal vez cometiste algún error al cambiar de rama y por por eso mantuvo la versión vieja.
Puedes elimina ese archivo sin ningún problema mientras tengas la última versión de import_graph.cc

**Comment by joseluishaddad** [comment]
Efectivamente me había equivocado en algún cambio de rama. 🤦‍♂️ borraré la issue!
Gracias
