### ISSUE TITLE
bug diferencia entre funciones estimate cost

### ISSUE THREAD

**Issue by jgespinosa10** [PUC-IIC3141/IIC3413-DB#4]
Hola,

Me dí cuenta que hay ocasiones en que las siguientes funciones retornan valores distintos:

NestedLoopPlan::estimate_cost(*x, *y);

y realizarlo de la siguiente forma:

unique_ptr\<JoinPlan> best = nullptr;
best = make_unique\<NestedLoopPlan>(x->duplicate(), y->duplicate());
best->estimate_cost();

No he logrado entender porque ocurre, pero tengo obtengo datos distintos al realizarlo de las dos formas.

**Comment by cirojas** [comment]
Tienes razón. EL error está en actualmente en la rama del lab 4, pero ya fue corregido en el proyecto original.

El valor más correcto es el que se genera a través del constructor. La razón es que `rhs->set_input_vars` no se estaba llamando en `NestedLoopPlan::estimate_cost`. Al final el método `NestedLoopPlan::estimate_cost` fue eliminado.
